<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl text-slate-800">Application #{{ $application->id }}</h2></x-slot>
<div class="py-8 bg-slate-50 min-h-screen"><div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
@if(session('success'))<div class="rounded-xl bg-emerald-50 border border-emerald-200 p-4 text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl bg-red-50 border border-red-200 p-4 text-red-700"><ul class="list-disc ml-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="bg-white rounded-2xl border shadow-sm p-6"><div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div class="text-sm text-slate-500">Application #{{ $application->id }}</div><h1 class="mt-1 text-2xl font-extrabold">{{ $application->service->name }}</h1><p class="mt-1 text-sm text-slate-500">Submitted {{ $application->created_at->format('d M Y, H:i') }}</p></div><span class="px-4 py-2 rounded-full bg-slate-100 font-bold">{{ ucfirst($application->status) }}</span></div>@if($application->notes)<div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><strong>Notes:</strong> {{ $application->notes }}</div>@endif</div>
<div class="bg-white rounded-2xl border shadow-sm p-6"><h2 class="text-xl font-bold">Document Requirements</h2><p class="text-sm text-slate-500 mt-1">Upload the documents requested for this service.</p><div class="mt-5 grid md:grid-cols-2 gap-3">
@forelse($application->service->documents->where('is_active',true) as $requirement)
@php $uploaded=$application->documents->first(fn($d)=>mb_strtolower($d->document_name)===mb_strtolower($requirement->name)); @endphp
<div class="rounded-xl border p-4 flex justify-between gap-3"><div><div class="font-semibold">{{ $requirement->name }}</div><div class="text-xs mt-1 {{ $requirement->is_required ? 'text-red-600':'text-slate-500' }}">{{ $requirement->is_required ? 'Required':'Optional' }}</div></div><span class="text-xs font-bold {{ $uploaded?'text-emerald-600':'text-amber-600' }}">{{ $uploaded?'Uploaded':'Pending' }}</span></div>
@empty<p class="text-slate-500">No document requirements configured.</p>@endforelse
</div>
<form method="POST" action="{{ route('application.documents.store',$application) }}" enctype="multipart/form-data" class="mt-7 grid md:grid-cols-2 gap-4">@csrf
<div><label class="block text-sm font-semibold mb-2" for="document_name">Document Name</label><select name="document_name" id="document_name" required class="w-full rounded-lg border-slate-300"><option value="">Select a requirement</option>@foreach($application->service->documents->where('is_active',true) as $requirement)<option value="{{ $requirement->name }}">{{ $requirement->name }}{{ $requirement->is_required?' *':'' }}</option>@endforeach</select></div>
<div><label class="block text-sm font-semibold mb-2" for="document">File (PDF/JPG/PNG, max 5MB)</label><input type="file" name="document" id="document" accept=".pdf,.jpg,.jpeg,.png" required class="w-full rounded-lg border-slate-300"></div>
<div class="md:col-span-2"><button class="px-5 py-2.5 rounded-lg bg-blue-600 text-white font-bold">Upload Document</button></div></form></div>
<div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h2 class="font-bold text-lg">Uploaded Documents</h2></div><div class="divide-y">
@forelse($application->documents as $document)<div class="p-5 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div class="font-bold">{{ $document->document_name }}</div><div class="text-sm text-slate-500">{{ $document->file_name }} · {{ number_format(($document->file_size??0)/1024,1) }} KB</div><div class="text-xs mt-1">Review status: <strong>{{ ucfirst($document->status) }}</strong></div></div><div class="flex gap-2"><a target="_blank" href="{{ asset('storage/'.$document->file_path) }}" class="px-4 py-2 rounded-lg border font-semibold">View</a>@if($document->status==='pending')<form method="POST" action="{{ route('application.documents.destroy',$document) }}">@csrf @method('DELETE')<button onclick="return confirm('Delete this document?')" class="px-4 py-2 rounded-lg bg-red-600 text-white font-semibold">Delete</button></form>@endif</div></div>
@empty<div class="p-10 text-center text-slate-500">No documents uploaded yet.</div>@endforelse
</div></div><a href="{{ route('customer.applications.index') }}" class="inline-block text-blue-600 font-bold">← Back to My Applications</a>
</div></div></x-app-layout>